sudo: required
services:
- docker
script:
- make check
deploy:
  provider: releases
  api_key:
    secure: g69d6cRBkVtxUStKwDecrLpHNtBqr/ftVCvYjasrmhEBdmxJvm9UDZFK5zUfuT9IWP015kWOhYetdcZ/KN+gz6i18vyan/0p2qk3QGoT9T4TKrh+FTN9wQlWnstktxqlY8PsOgJ+JEwzwjHy7J2W44RHsrI0dBTujIKbPPwYAgMcUzdCp6JBXqAH/cyzXxFl3P/k6CHFAQwR8xRDgnMrgLwRAn9R1PF1ILd2grDN+SFTWGGXUs+WoFLxGKq6sMa2BIlJx7VT3na+sOpOV/fb8uidK2TX/X7hHSk7pIfzlaSqsyDfIkx8MqzypQKctghCegYPthpVbWpa8v44o98aPu3j2/A2cFwGVVaCqcdLTkbx5TuQ0GWykJU+/uXV+rLBdq2kbTKiWPxjhNdNVu3xxBHPRTJxTaF5l0a4SufTduQmYgzvbxuN2ICAihpJ0hQ4FeUGeR6If2AmGYoPU9cK1PaHJQz0XV/GqLwkAVubnJFT3COhw+a2B7r7t57Fep7mLKsXf4sJXMcxrwRIrPCCdRmzhfNZMAAy2gD+HYU+Q6lPZedBWuUPutLLeOr29TyFnPLnM+xlEBqLQA1VUTow0a25OfYEmhS9MZSpHMz8oJZp63ZLpmkaYET0JxShCiCed5AolaD5gjoMD5AghmBUqy/QrxtORkcnsS5TK+K4N0I=
  file: k8spkg
  skip_cleanup: true
  on:
    repo: mgoltzsche/k8spkg
    tags: true
